
server:
  port: 8090

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: greenlc
    password: greenlc

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/greenlc
    username: greenlc
    password: greenlc

  jpa:
    hibernate:
      ddl-auto: update # Use update for development, none for production
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
